### ISSUE TITLE
Manifest URL Error

### ISSUE THREAD

**Issue by DarkBearmancula** [vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT#4]
### What's wrong?

Attempting to install this module presents the following error: 
![image](https://github.com/vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT/assets/73794994/c43cd93f-608f-4f00-b5d6-c6425baf43a1)

Visiting the module's page on Foundry, if I scroll to open the manifest URL manually it directs to the following:
![image](https://github.com/vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT/assets/73794994/424b5e82-2900-485d-8aa7-4945b267fae7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WildBillLives** [comment]
Just purchased the module, I get the same error as above- from the console:

`Error: Unable to load valid module manifest data from "https://github.com/vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT/releases/download/1.0.3/module.json"
No module manifest found at https://github.com/vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT/releases/download/1.0.3/module.json
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2076)
fetch @ foundry.js:67600
notify @ foundry.js:67497
error @ foundry.js:67534
post @ setup.js:3899
await in post (async)
(anonymous) @ setup.js:3493
installPackage @ setup.js:3432
#onClickPackageInstall @ setup.js:2948
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2`

I was able to install the 1.02 release by going to the following URL:
https://github.com/vttred/The-Isle-of-the-Plangent-Mage-for-Foundry-VTT/releases

**Comment by DarkBearmancula** [comment]
I was able to install the module this evening. The issue appears to be resolved. Thank you!

**Comment by anthonyronda** [comment]
Thanks for reporting folks!

Some wires got crossed in my brain, and I made a "1.0.3" update on the Foundry admin console that doesn't exist yet. Rest assured updates are still coming and Plangent Mage isn't far behind in getting a map notes update.
